application: superwar3fan
version: 1
runtime: python
api_version: 1

handlers:

- url: /styles
  static_dir: styles

- url: /rss\.png
  static_files: images/rss.png
  upload: images/rss.png

- url: /scripts
  static_dir: scripts

- url: /admin
  script: admin.py

- url: /admin/blog/.*
  script: admin.py

- url: /admin/category/.*
  script: admin.py
  
- url: /
  script: main.py

- url: /page/.*
  script: main.py

- url: /api/.*
  script: apis.py

- url: /view
  script: apis.py

- url: /blog/.*
  script: main.py

- url: /category/.*
  script: main.py

- url: /comment/.*
  script: main.py