application: superwar3fan
version: 1
runtime: python
api_version: 1

handlers:

- url: /styles
  static_dir: styles
  
- url: /
  script: main.py

- url: /blog/.*
  script: main.py

- url: /category/.*
  script: main.py

- url: /comment/.*
  script: main.py