application: superwar3fan
version: 2
runtime: python
api_version: 1

handlers:

- url: /styles
  static_dir: styles

- url: /rss\.png
  static_files: images/rss.png
  upload: images/rss.png

- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico

- url: /scripts
  static_dir: scripts

- url: /admin
  script: admin.py
  login: admin

- url: /admin/blog/.*
  script: admin.py
  login: admin

- url: /admin/category/.*
  script: admin.py
  login: admin
  
- url: /
  script: main.py

- url: /page/.*
  script: main.py

- url: /api/.*
  script: apis.py

- url: /view
  script: apis.py

- url: /blog/rss
  script: BlogRss.py

- url: /blog/rss/category/.*
  script: BlogRss.py

- url: /blog/.*
  script: main.py

- url: /category/.*
  script: main.py

- url: /comment/.*
  script: main.py

- url: /Olympic/.*
  script: Olympic.py

- url: /Olympic
  script: Olympic.py

- url: /Intrepid
  script: Intrepid.py

- url: /Intrepid/.*
  script: Intrepid.py